name: Gain package

on: [pull_request]

env:
  TEST_PRINT_MAPS_AND_FDS: true
  TEST_LOGGER_LEVEL: trace

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get .

      - name: Run coverage
        run: go test -v ./... -timeout 10s -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
