name: Gain package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: kenchan0130/actions-system-info@master
        id: system-info
      
      - name: Check outputs
        run: |
          OUTPUTS=(
            "CPU Core: ${{ steps.system-info.outputs.cpu-core }}"
            "CPU Model: ${{ steps.system-info.outputs.cpu-model }}"
            "Hostname: ${{ steps.system-info.outputs.hostname }}"
            "Kernel release: ${{ steps.system-info.outputs.kernel-release }}"
            "Kernel version: ${{ steps.system-info.outputs.kernel-version }}"
            "Name: ${{ steps.system-info.outputs.name }}"
            "Platform: ${{ steps.system-info.outputs.platform }}"
            "Release: ${{ steps.system-info.outputs.release }}"
            "Total memory bytes: ${{ steps.system-info.outputs.totalmem }}"
          )
          IS_EMPTY_OUTOUT=false
          for OUTPUT in "${OUTPUTS[@]}";do
            echo "${OUTPUT}"
            OUT=$(echo ${OUTPUT} | cut -d ':' -f2- | xargs)
            if [[ -z "${OUT}" ]];then
              IS_EMPTY_OUTOUT=true
            fi
          done
          if "$IS_EMPTY_OUTOUT";then
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get .

      - name: Run coverage
        run: go test -v ./... -timeout 10s -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
